[package]
name    = "antigravity-yield"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name       = "antigravity_yield"

[features]
no-entrypoint = []
no-idl        = []
no-log-ix-name = []
cpi           = ["no-entrypoint"]
default       = []

[dependencies]
anchor-lang = { version = "0.31.0", features = ["init-if-needed"] }
anchor-spl  = { version = "0.31.0", features = ["token_2022", "associated_token"] }
spl-token-2022 = { version = "4.0.0", features = ["no-entrypoint"] }
